import {
  Hotspot,
  SensorObservation,
  CitizenReport,
  EnvironmentalAlert,
  CityForecast,
  FederatedCityNode,
  FederatedModelUpdate,
  EnvironmentalEvent,
  DashboardMetrics,
} from './types';

export const initialMetrics: DashboardMetrics = {
  airQuality: 287,
  activeHotspots: 27,
  predictiveAlerts: 8,
  connectedCities: 12,
  overallHealthStatus: 'POOR',
  nationalAverageAqi: 214,
  activeSensors: 148,
  pendingReports: 6,
  totalModelUpdates: 1284,
};

export const initialHotspots: Hotspot[] = [
  {
    id: 'hotspot-pune-corridor',
    name: 'Pune Industrial Corridor',
    city: 'Pune',
    state: 'Maharashtra',
    coordinates: { lat: 18.6279, lng: 73.8009 },
    aqi: 287,
    risk: 'HIGH',
    confidence: 91,
    detectedAgo: '14 min ago',
    detectedTimestamp: new Date(Date.now() - 14 * 60000).toISOString(),
    primaryPollutant: 'PM2.5',
    affectedRadiusKm: 14.5,
    corridorName: 'Bhosari-Chakan Logistics Belt',
    recommendedAction: 'Environmental field inspection',
    signals: [
      {
        id: 'sig-1',
        type: 'Sensor anomaly',
        label: 'Continuous PM2.5 gradient step',
        value: '+114 µg/m³ above baseline',
        timestamp: '14 min ago',
        status: 'severe',
      },
      {
        id: 'sig-2',
        type: 'Citizen observation',
        label: 'Industrial exhaust plume flagged',
        value: '3 photographic reports',
        timestamp: '22 min ago',
        status: 'elevated',
      },
      {
        id: 'sig-3',
        type: 'Satellite signal',
        label: 'Sentinel-5P Tropospheric NO2 plume',
        value: 'Aerosol Optical Depth 0.82',
        timestamp: '45 min ago',
        status: 'severe',
      },
      {
        id: 'sig-4',
        type: 'Meteorological condition',
        label: 'Boundary layer wind shear calm',
        value: 'Wind velocity 1.8 km/h, Stagnation index 89%',
        timestamp: '10 min ago',
        status: 'severe',
      },
    ],
    explainability: [
      {
        factor: 'Industrial activity',
        percentage: 42,
        description: 'Coordinated thermal stack releases in fabrication & metallurgy clusters.',
      },
      {
        factor: 'Wind stagnation',
        percentage: 27,
        description: 'Micro-valley thermal trapping preventing planetary dispersion.',
      },
      {
        factor: 'Sensor anomaly',
        percentage: 18,
        description: 'Corroborated sudden gradient deviations across 4 neighboring IoT nodes.',
      },
      {
        factor: 'Satellite signal',
        percentage: 9,
        description: 'Correlated tropospheric column NO2 concentration patch.',
      },
      {
        factor: 'Historical pattern',
        percentage: 4,
        description: 'Seasonal post-monsoon diurnal thermal inversion recurrence.',
      },
    ],
    predictionChart: [
      { timeLabel: 'Now', hoursAhead: 0, aqi: 287, confidenceInterval: [280, 294] },
      { timeLabel: '+2h', hoursAhead: 2, aqi: 304, confidenceInterval: [292, 318] },
      { timeLabel: '+4h', hoursAhead: 4, aqi: 326, confidenceInterval: [310, 342] },
      { timeLabel: '+6h', hoursAhead: 6, aqi: 345, confidenceInterval: [325, 365] },
      { timeLabel: '+12h', hoursAhead: 12, aqi: 298, confidenceInterval: [270, 320] },
      { timeLabel: '+24h', hoursAhead: 24, aqi: 240, confidenceInterval: [215, 265] },
    ],
  },
  {
    id: 'hotspot-pune-chakan',
    name: 'Chakan Phase-II Industrial Hub',
    city: 'Pune',
    state: 'Maharashtra',
    coordinates: { lat: 18.7580, lng: 73.8580 },
    aqi: 242,
    risk: 'HIGH',
    confidence: 88,
    detectedAgo: '20 min ago',
    detectedTimestamp: new Date(Date.now() - 20 * 60000).toISOString(),
    primaryPollutant: 'PM10',
    affectedRadiusKm: 11.0,
    corridorName: 'Talegaon-Chakan Auto Belt',
    recommendedAction: 'Inspect automotive spray booths and foundry exhausts',
    signals: [
      {
        id: 'chk-sig-1',
        type: 'Sensor anomaly',
        label: 'Auto cluster sensor threshold spike',
        value: 'PM10: 195 µg/m³',
        timestamp: '20 min ago',
        status: 'severe',
      },
      {
        id: 'chk-sig-2',
        type: 'Citizen observation',
        label: 'Field biomass and paint plume reported',
        value: 'Crop burning in nearby buffer',
        timestamp: '25 min ago',
        status: 'elevated',
      },
    ],
    explainability: [
      { factor: 'Industrial activity', percentage: 40, description: 'Foundry melting furnaces and fabrication.' },
      { factor: 'Agricultural burning', percentage: 32, description: 'Farmland crop residue burning in buffer villages.' },
      { factor: 'Low Wind', percentage: 20, description: 'Low wind velocity trapping smoke in valley basin.' },
      { factor: 'Heavy transport logistics', percentage: 8, description: 'Container truck idling on Spine Road.' },
    ],
    predictionChart: [
      { timeLabel: 'Now', hoursAhead: 0, aqi: 242, confidenceInterval: [235, 250] },
      { timeLabel: '+2h', hoursAhead: 2, aqi: 260, confidenceInterval: [248, 275] },
      { timeLabel: '+4h', hoursAhead: 4, aqi: 280, confidenceInterval: [265, 295] },
      { timeLabel: '+6h', hoursAhead: 6, aqi: 265, confidenceInterval: [250, 280] },
      { timeLabel: '+12h', hoursAhead: 12, aqi: 215, confidenceInterval: [195, 235] },
      { timeLabel: '+24h', hoursAhead: 24, aqi: 170, confidenceInterval: [150, 190] },
    ],
  },
  {
    id: 'hotspot-delhi-anand-vihar',
    name: 'Delhi Anand Vihar Intermodal Corridor',
    city: 'Delhi',
    state: 'National Capital Region',
    coordinates: { lat: 28.6469, lng: 77.3164 },
    aqi: 384,
    risk: 'CRITICAL',
    confidence: 96,
    detectedAgo: '8 min ago',
    detectedTimestamp: new Date(Date.now() - 8 * 60000).toISOString(),
    primaryPollutant: 'PM2.5',
    affectedRadiusKm: 22.0,
    corridorName: 'Delhi-Ghaziabad Transit Frontier',
    recommendedAction: 'Immediate anti-smog water cannon deployment & heavy traffic diversion',
    signals: [
      {
        id: 'del-sig-1',
        type: 'Sensor anomaly',
        label: 'CPCB Grid Station #12 Critical Spike',
        value: 'PM2.5: 395 µg/m³',
        timestamp: '8 min ago',
        status: 'severe',
      },
      {
        id: 'del-sig-2',
        type: 'Citizen observation',
        label: 'Transit terminal dust & low idling smoke',
        value: '12 citizen alerts logged',
        timestamp: '18 min ago',
        status: 'severe',
      },
      {
        id: 'del-sig-3',
        type: 'Satellite signal',
        label: 'MODIS thermal fire spot adjacency',
        value: 'FRP 34.2 MW north-west upwind',
        timestamp: '1 hour ago',
        status: 'elevated',
      },
      {
        id: 'del-sig-4',
        type: 'Meteorological condition',
        label: 'Severe nocturnal surface inversion',
        value: 'Inversion base 80m, wind 0.9 km/h',
        timestamp: '12 min ago',
        status: 'severe',
      },
    ],
    explainability: [
      { factor: 'Industrial & transit emissions', percentage: 48, description: 'Interstate bus fleets + border freight idling.' },
      { factor: 'Regional biomass drift', percentage: 24, description: 'North-western agricultural burn transport vector.' },
      { factor: 'Temperature inversion', percentage: 18, description: 'Shallow nocturnal boundary layer trap.' },
      { factor: 'Road dust suspension', percentage: 10, description: 'Unpaved corridor road friction.' },
    ],
    predictionChart: [
      { timeLabel: 'Now', hoursAhead: 0, aqi: 384, confidenceInterval: [375, 395] },
      { timeLabel: '+2h', hoursAhead: 2, aqi: 412, confidenceInterval: [398, 430] },
      { timeLabel: '+4h', hoursAhead: 4, aqi: 435, confidenceInterval: [415, 455] },
      { timeLabel: '+6h', hoursAhead: 6, aqi: 410, confidenceInterval: [385, 435] },
      { timeLabel: '+12h', hoursAhead: 12, aqi: 350, confidenceInterval: [320, 380] },
      { timeLabel: '+24h', hoursAhead: 24, aqi: 290, confidenceInterval: [260, 320] },
    ],
  },
  {
    id: 'hotspot-mumbai-chembur',
    name: 'Mumbai Chembur-Trombay Petrochemical Corridor',
    city: 'Mumbai',
    state: 'Maharashtra',
    coordinates: { lat: 19.0178, lng: 72.9056 },
    aqi: 245,
    risk: 'HIGH',
    confidence: 88,
    detectedAgo: '32 min ago',
    detectedTimestamp: new Date(Date.now() - 32 * 60000).toISOString(),
    primaryPollutant: 'SO2',
    affectedRadiusKm: 11.2,
    corridorName: 'Mahul Industrial Refinery Arc',
    recommendedAction: 'Verify catalytic cracker scrubber emission logs',
    signals: [
      {
        id: 'mum-sig-1',
        type: 'Sensor anomaly',
        label: 'SO2 sensor cluster spike',
        value: 'SO2: 142 µg/m³',
        timestamp: '32 min ago',
        status: 'severe',
      },
      {
        id: 'mum-sig-2',
        type: 'Meteorological condition',
        label: 'Sea breeze deceleration',
        value: 'Coastal eddy trapping plume inland',
        timestamp: '25 min ago',
        status: 'elevated',
      },
    ],
    explainability: [
      { factor: 'Petrochemical refinery venting', percentage: 54, description: 'Flare stack output in petrochemical complex.' },
      { factor: 'Harbor marine transport', percentage: 22, description: 'Heavy marine bunker fuel combustion.' },
      { factor: 'Local wind shear eddy', percentage: 16, description: 'Coast-to-inland stagnation.' },
      { factor: 'Traffic bottleneck', percentage: 8, description: 'Eastern freeway heavy goods transit.' },
    ],
    predictionChart: [
      { timeLabel: 'Now', hoursAhead: 0, aqi: 245, confidenceInterval: [238, 252] },
      { timeLabel: '+2h', hoursAhead: 2, aqi: 260, confidenceInterval: [248, 272] },
      { timeLabel: '+4h', hoursAhead: 4, aqi: 275, confidenceInterval: [260, 290] },
      { timeLabel: '+6h', hoursAhead: 6, aqi: 250, confidenceInterval: [235, 265] },
      { timeLabel: '+12h', hoursAhead: 12, aqi: 195, confidenceInterval: [180, 215] },
      { timeLabel: '+24h', hoursAhead: 24, aqi: 165, confidenceInterval: [150, 180] },
    ],
  },
  {
    id: 'hotspot-ahmedabad-vatva',
    name: 'Ahmedabad Vatva GIDC Chemical Belt',
    city: 'Ahmedabad',
    state: 'Gujarat',
    coordinates: { lat: 22.9567, lng: 72.6322 },
    aqi: 272,
    risk: 'HIGH',
    confidence: 89,
    detectedAgo: '19 min ago',
    detectedTimestamp: new Date(Date.now() - 19 * 60000).toISOString(),
    primaryPollutant: 'NO2',
    affectedRadiusKm: 13.0,
    corridorName: 'Vatva-Narol Industrial Expressway',
    recommendedAction: 'Deploy CETP emission audit team & enforce stack monitoring',
    signals: [
      {
        id: 'ahm-sig-1',
        type: 'Sensor anomaly',
        label: 'VOC & NO2 elevated co-gradient',
        value: 'NO2: 128 µg/m³',
        timestamp: '19 min ago',
        status: 'severe',
      },
      {
        id: 'ahm-sig-2',
        type: 'Satellite signal',
        label: 'TROPOMI tropospheric nitrogen dioxide spike',
        value: 'Column density 1.4x baseline',
        timestamp: '50 min ago',
        status: 'elevated',
      },
    ],
    explainability: [
      { factor: 'Chemical boiler emissions', percentage: 46, description: 'Small to medium dyestuff manufacturing boilers.' },
      { factor: 'Arid dust resuspension', percentage: 26, description: 'Dry alluvial soil particulate dispersion.' },
      { factor: 'Nighttime micro-climate calm', percentage: 20, description: 'Zero convective mixing over alluvial plain.' },
      { factor: 'Industrial freight corridors', percentage: 8, description: 'Heavy diesel carrier transit.' },
    ],
    predictionChart: [
      { timeLabel: 'Now', hoursAhead: 0, aqi: 272, confidenceInterval: [265, 280] },
      { timeLabel: '+2h', hoursAhead: 2, aqi: 290, confidenceInterval: [278, 305] },
      { timeLabel: '+4h', hoursAhead: 4, aqi: 310, confidenceInterval: [295, 325] },
      { timeLabel: '+6h', hoursAhead: 6, aqi: 295, confidenceInterval: [280, 312] },
      { timeLabel: '+12h', hoursAhead: 12, aqi: 230, confidenceInterval: [210, 250] },
      { timeLabel: '+24h', hoursAhead: 24, aqi: 185, confidenceInterval: [170, 200] },
    ],
  },
  {
    id: 'hotspot-bengaluru-peenya',
    name: 'Bengaluru Peenya Industrial Cluster',
    city: 'Bengaluru',
    state: 'Karnataka',
    coordinates: { lat: 13.0285, lng: 77.5195 },
    aqi: 168,
    risk: 'MODERATE',
    confidence: 84,
    detectedAgo: '41 min ago',
    detectedTimestamp: new Date(Date.now() - 41 * 60000).toISOString(),
    primaryPollutant: 'PM10',
    affectedRadiusKm: 8.5,
    corridorName: 'Tumkur Road Manufacturing Corridor',
    recommendedAction: 'Automated road sweeping and warehouse emission check',
    signals: [
      {
        id: 'blr-sig-1',
        type: 'Sensor anomaly',
        label: 'Coarse particulate surge',
        value: 'PM10: 178 µg/m³',
        timestamp: '41 min ago',
        status: 'elevated',
      },
      {
        id: 'blr-sig-2',
        type: 'Citizen observation',
        label: 'Demolition dust unshielded',
        value: '1 citizen photo submitted',
        timestamp: '1 hour ago',
        status: 'nominal',
      },
    ],
    explainability: [
      { factor: 'Construction & road resurfacing', percentage: 38, description: 'Metro line expansion dust plume.' },
      { factor: 'Light fabrication machinery', percentage: 32, description: 'Electroplating & metal cutting units.' },
      { factor: 'Heavy vehicular transit', percentage: 22, description: 'National Highway 48 freight movement.' },
      { factor: 'Vegetation wind shielding', percentage: 8, description: 'Localized wind deceleration in industrial valleys.' },
    ],
    predictionChart: [
      { timeLabel: 'Now', hoursAhead: 0, aqi: 168, confidenceInterval: [160, 175] },
      { timeLabel: '+2h', hoursAhead: 2, aqi: 180, confidenceInterval: [170, 192] },
      { timeLabel: '+4h', hoursAhead: 4, aqi: 195, confidenceInterval: [182, 210] },
      { timeLabel: '+6h', hoursAhead: 6, aqi: 175, confidenceInterval: [162, 190] },
      { timeLabel: '+12h', hoursAhead: 12, aqi: 145, confidenceInterval: [130, 160] },
      { timeLabel: '+24h', hoursAhead: 24, aqi: 120, confidenceInterval: [105, 135] },
    ],
  },
  {
    id: 'hotspot-hyderabad-patancheru',
    name: 'Hyderabad Patancheru Chemical Cluster',
    city: 'Hyderabad',
    state: 'Telangana',
    coordinates: { lat: 17.5284, lng: 78.2678 },
    aqi: 238,
    risk: 'HIGH',
    confidence: 87,
    detectedAgo: '28 min ago',
    detectedTimestamp: new Date(Date.now() - 28 * 60000).toISOString(),
    primaryPollutant: 'PM2.5',
    affectedRadiusKm: 12.0,
    corridorName: 'Outer Ring Road Pharma Industrial Spine',
    recommendedAction: 'Dispatch TS-PCB monitoring van for solvent vapor scan',
    signals: [
      {
        id: 'hyd-sig-1',
        type: 'Sensor anomaly',
        label: 'Organic particulate elevation',
        value: 'PM2.5: 112 µg/m³',
        timestamp: '28 min ago',
        status: 'severe',
      },
    ],
    explainability: [
      { factor: 'Bulk active pharma formulation', percentage: 45, description: 'Synthetic chemical active drug manufacturing.' },
      { factor: 'Solid fuel industrial boilers', percentage: 30, description: 'Briquette & coal fired utility plants.' },
      { factor: 'Inversion cap', percentage: 15, description: 'Deccan plateau nocturnal stability.' },
      { factor: 'Heavy transport logistics', percentage: 10, description: 'Supply chain carrier idle periods.' },
    ],
    predictionChart: [
      { timeLabel: 'Now', hoursAhead: 0, aqi: 238, confidenceInterval: [230, 245] },
      { timeLabel: '+2h', hoursAhead: 2, aqi: 255, confidenceInterval: [244, 268] },
      { timeLabel: '+4h', hoursAhead: 4, aqi: 270, confidenceInterval: [256, 285] },
      { timeLabel: '+6h', hoursAhead: 6, aqi: 240, confidenceInterval: [225, 255] },
      { timeLabel: '+12h', hoursAhead: 12, aqi: 180, confidenceInterval: [165, 195] },
      { timeLabel: '+24h', hoursAhead: 24, aqi: 140, confidenceInterval: [125, 155] },
    ],
  },
  {
    id: 'hotspot-kolkata-haldia',
    name: 'Kolkata Haldia Industrial Gateway',
    city: 'Kolkata',
    state: 'West Bengal',
    coordinates: { lat: 22.0624, lng: 88.0645 },
    aqi: 260,
    risk: 'HIGH',
    confidence: 86,
    detectedAgo: '35 min ago',
    detectedTimestamp: new Date(Date.now() - 35 * 60000).toISOString(),
    primaryPollutant: 'SO2',
    affectedRadiusKm: 15.0,
    corridorName: 'Hooghly Estuary Port & Petrochemical Belt',
    recommendedAction: 'Engage port authority for wet bulk handling dampening',
    signals: [
      {
        id: 'kol-sig-1',
        type: 'Sensor anomaly',
        label: 'Sulfur and carbonaceous particulate surge',
        value: 'AQI index 260',
        timestamp: '35 min ago',
        status: 'severe',
      },
    ],
    explainability: [
      { factor: 'Petrochemical cracking & fertilizers', percentage: 44, description: 'Heavy ammonia and acid manufacturing stacks.' },
      { factor: 'River barge diesel emissions', percentage: 26, description: 'Inland water transport diesel generators.' },
      { factor: 'High relative humidity fog mix', percentage: 20, description: 'Estuarine vapor condensing with particulate matter.' },
      { factor: 'Thermal power plant fly ash', percentage: 10, description: 'Adjacent power generation electrostatic precipitator load.' },
    ],
    predictionChart: [
      { timeLabel: 'Now', hoursAhead: 0, aqi: 260, confidenceInterval: [250, 270] },
      { timeLabel: '+2h', hoursAhead: 2, aqi: 275, confidenceInterval: [262, 290] },
      { timeLabel: '+4h', hoursAhead: 4, aqi: 290, confidenceInterval: [275, 308] },
      { timeLabel: '+6h', hoursAhead: 6, aqi: 265, confidenceInterval: [250, 280] },
      { timeLabel: '+12h', hoursAhead: 12, aqi: 210, confidenceInterval: [195, 230] },
      { timeLabel: '+24h', hoursAhead: 24, aqi: 175, confidenceInterval: [160, 195] },
    ],
  },
  {
    id: 'hotspot-chennai-manali',
    name: 'Chennai Manali Petrochemical Zone',
    city: 'Chennai',
    state: 'Tamil Nadu',
    coordinates: { lat: 13.1672, lng: 80.2587 },
    aqi: 154,
    risk: 'MODERATE',
    confidence: 82,
    detectedAgo: '50 min ago',
    detectedTimestamp: new Date(Date.now() - 50 * 60000).toISOString(),
    primaryPollutant: 'SO2',
    affectedRadiusKm: 9.0,
    corridorName: 'North Chennai Industrial Basin',
    recommendedAction: 'Automated continuous ambient air monitoring verification',
    signals: [
      {
        id: 'che-sig-1',
        type: 'Sensor anomaly',
        label: 'Moderate SO2 drift over residential periphery',
        value: 'SO2: 68 µg/m³',
        timestamp: '50 min ago',
        status: 'elevated',
      },
    ],
    explainability: [
      { factor: 'Refinery distillates handling', percentage: 40, description: 'Storage tank breathing emissions.' },
      { factor: 'Port container transit', percentage: 30, description: 'Container trailer queue idling.' },
      { factor: 'Coastal thermal stability', percentage: 18, description: 'Land-sea breeze transition boundary.' },
      { factor: 'Construction dust', percentage: 12, description: 'Outer ring arterial expansion work.' },
    ],
    predictionChart: [
      { timeLabel: 'Now', hoursAhead: 0, aqi: 154, confidenceInterval: [148, 162] },
      { timeLabel: '+2h', hoursAhead: 2, aqi: 165, confidenceInterval: [155, 176] },
      { timeLabel: '+4h', hoursAhead: 4, aqi: 178, confidenceInterval: [166, 190] },
      { timeLabel: '+6h', hoursAhead: 6, aqi: 160, confidenceInterval: [148, 172] },
      { timeLabel: '+12h', hoursAhead: 12, aqi: 135, confidenceInterval: [122, 148] },
      { timeLabel: '+24h', hoursAhead: 24, aqi: 110, confidenceInterval: [98, 125] },
    ],
  },
];

export const initialAlerts: EnvironmentalAlert[] = [
  {
    id: 'alert-pc-01',
    title: 'Pimpri-Chinchwad Industrial Zone',
    hotspotId: 'hotspot-pune-corridor',
    locationName: 'Pimpri-Chinchwad Industrial Zone',
    city: 'Pune',
    coordinates: { lat: 18.6279, lng: 73.8009 },
    currentAqi: 287,
    predictedAqi: 312,
    expectedDurationHours: '4–7 hours',
    risk: 'HIGH',
    suggestedResponse: 'Field inspection',
    status: 'ALERT_SENT',
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60000).toISOString(),
    assignedAuthority: 'Maharashtra Pollution Control Board (Regional Office Pune)',
    actionLog: [
      {
        status: 'DETECTED',
        updatedAt: new Date(Date.now() - 45 * 60000).toISOString(),
        actor: 'AEROVEDA Detection Engine',
        note: 'Continuous PM2.5 gradient step of +114 µg/m³ detected across 4 IoT sensors.',
      },
      {
        status: 'VALIDATED',
        updatedAt: new Date(Date.now() - 30 * 60000).toISOString(),
        actor: 'AI Multi-Modal Fusion Engine',
        note: 'Cross-validated against Sentinel-5P NO2 tropospheric column and 3 citizen alerts.',
      },
      {
        status: 'ALERT_SENT',
        updatedAt: new Date(Date.now() - 15 * 60000).toISOString(),
        actor: 'Automated Dispatch Gateway',
        note: 'Priority 1 dispatch routed to MPCB Rapid Response Field Team & PMC Ward Office.',
      },
    ],
  },
  {
    id: 'alert-delhi-02',
    title: 'Anand Vihar - Kaushambi Transit Junction',
    hotspotId: 'hotspot-delhi-anand-vihar',
    locationName: 'Anand Vihar - Kaushambi Transit Junction',
    city: 'Delhi',
    coordinates: { lat: 28.6469, lng: 77.3164 },
    currentAqi: 384,
    predictedAqi: 435,
    expectedDurationHours: '6–10 hours',
    risk: 'CRITICAL',
    suggestedResponse: 'Anti-smog mist cannon deployment & interstate truck diversion',
    status: 'INVESTIGATING',
    createdAt: new Date(Date.now() - 75 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString(),
    assignedAuthority: 'Delhi Pollution Control Committee & Traffic Police',
    actionLog: [
      { status: 'DETECTED', updatedAt: new Date(Date.now() - 75 * 60000).toISOString(), actor: 'AEROVEDA Detection Engine', note: 'Severe particulate spike exceeding 380 AQI' },
      { status: 'VALIDATED', updatedAt: new Date(Date.now() - 60 * 60000).toISOString(), actor: 'System Auditor', note: 'Ground sensor validation confirmed' },
      { status: 'ALERT_SENT', updatedAt: new Date(Date.now() - 45 * 60000).toISOString(), actor: 'Alert Dispatch', note: 'DPCC emergency notification emitted' },
      { status: 'ACKNOWLEDGED', updatedAt: new Date(Date.now() - 30 * 60000).toISOString(), actor: 'DPCC Control Desk', note: 'Desk officer acknowledged incident ticket' },
      { status: 'INVESTIGATING', updatedAt: new Date(Date.now() - 10 * 60000).toISOString(), actor: 'East Delhi Mobile Unit 04', note: 'Patrol on-site conducting mist spraying and enforcing truck idling ban' },
    ],
  },
  {
    id: 'alert-vatva-03',
    title: 'Vatva Chemical Estate - Phase IV',
    hotspotId: 'hotspot-ahmedabad-vatva',
    locationName: 'Vatva Chemical Estate - Phase IV',
    city: 'Ahmedabad',
    coordinates: { lat: 22.9567, lng: 72.6322 },
    currentAqi: 272,
    predictedAqi: 310,
    expectedDurationHours: '3–5 hours',
    risk: 'HIGH',
    suggestedResponse: 'Emission compliance inspection at textile boiler stacks',
    status: 'ACKNOWLEDGED',
    createdAt: new Date(Date.now() - 90 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 25 * 60000).toISOString(),
    assignedAuthority: 'Gujarat Pollution Control Board (Ahmedabad Regional Office)',
    actionLog: [
      { status: 'DETECTED', updatedAt: new Date(Date.now() - 90 * 60000).toISOString(), actor: 'Sensor Anomaly Engine', note: 'NO2 elevation step detected' },
      { status: 'VALIDATED', updatedAt: new Date(Date.now() - 70 * 60000).toISOString(), actor: 'AI Fusion', note: 'Satellite confirmation received' },
      { status: 'ALERT_SENT', updatedAt: new Date(Date.now() - 50 * 60000).toISOString(), actor: 'Automated Dispatch', note: 'GPCB zonal team alerted' },
      { status: 'ACKNOWLEDGED', updatedAt: new Date(Date.now() - 25 * 60000).toISOString(), actor: 'GPCB Inspector R. Mehta', note: 'Assigned to field squad for evening shift inspection' },
    ],
  },
  {
    id: 'alert-chembur-04',
    title: 'Chembur Mahul Coastal Flare Boundary',
    hotspotId: 'hotspot-mumbai-chembur',
    locationName: 'Chembur Mahul Coastal Flare Boundary',
    city: 'Mumbai',
    coordinates: { lat: 19.0178, lng: 72.9056 },
    currentAqi: 245,
    predictedAqi: 275,
    expectedDurationHours: '4–6 hours',
    risk: 'HIGH',
    suggestedResponse: 'Verify sulfur recovery unit flaring rate',
    status: 'VALIDATED',
    createdAt: new Date(Date.now() - 40 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60000).toISOString(),
    assignedAuthority: 'MPCB Mumbai Coastal Zonal Office',
    actionLog: [
      { status: 'DETECTED', updatedAt: new Date(Date.now() - 40 * 60000).toISOString(), actor: 'AEROVEDA Detection Engine', note: 'Localized SO2 plume' },
      { status: 'VALIDATED', updatedAt: new Date(Date.now() - 20 * 60000).toISOString(), actor: 'Automated Classifier', note: 'Confirmed non-biogenic sulfur signature' },
    ],
  },
  {
    id: 'alert-delhi-okhla-05',
    title: 'Okhla Industrial Area Phase-II',
    locationName: 'Okhla Industrial Area Phase-II',
    city: 'Delhi',
    coordinates: { lat: 28.5284, lng: 77.2785 },
    currentAqi: 362,
    predictedAqi: 395,
    expectedDurationHours: '5–8 hours',
    risk: 'CRITICAL',
    suggestedResponse: 'Waste-to-energy plant stack verification & illegal dumping crackdown',
    status: 'DETECTED',
    createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60000).toISOString(),
    assignedAuthority: 'DPCC South Delhi Enforcement Wing',
    actionLog: [
      { status: 'DETECTED', updatedAt: new Date(Date.now() - 12 * 60000).toISOString(), actor: 'AEROVEDA Detection Engine', note: 'Particulate spike with high carbon black signature' },
    ],
  },
  {
    id: 'alert-patancheru-06',
    title: 'Patancheru Industrial Estate Gate 2',
    hotspotId: 'hotspot-hyderabad-patancheru',
    locationName: 'Patancheru Industrial Estate Gate 2',
    city: 'Hyderabad',
    coordinates: { lat: 17.5284, lng: 78.2678 },
    currentAqi: 238,
    predictedAqi: 270,
    expectedDurationHours: '3–6 hours',
    risk: 'HIGH',
    suggestedResponse: 'Audit nocturnal solvent recovery units',
    status: 'RESOLVED',
    createdAt: new Date(Date.now() - 180 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 35 * 60000).toISOString(),
    assignedAuthority: 'Telangana State Pollution Control Board',
    actionLog: [
      { status: 'DETECTED', updatedAt: new Date(Date.now() - 180 * 60000).toISOString(), actor: 'AEROVEDA Sensor Grid', note: 'VOC spike' },
      { status: 'VALIDATED', updatedAt: new Date(Date.now() - 160 * 60000).toISOString(), actor: 'AEROVEDA AI', note: 'Confirmed localized solvent event' },
      { status: 'ALERT_SENT', updatedAt: new Date(Date.now() - 140 * 60000).toISOString(), actor: 'Alert Dispatch', note: 'Dispatched to TSPCB zonal office' },
      { status: 'ACKNOWLEDGED', updatedAt: new Date(Date.now() - 120 * 60000).toISOString(), actor: 'Inspector K. Reddy', note: 'Ticket taken up' },
      { status: 'INVESTIGATING', updatedAt: new Date(Date.now() - 90 * 60000).toISOString(), actor: 'TSPCB Squad', note: 'Inspected Unit 7 condenser leak' },
      { status: 'RESOLVED', updatedAt: new Date(Date.now() - 35 * 60000).toISOString(), actor: 'TSPCB Squad', note: 'Condenser leak isolated and emissions normalized to 110 AQI' },
    ],
  },
  {
    id: 'alert-peenya-07',
    title: 'Peenya 4th Phase Machinery Hub',
    hotspotId: 'hotspot-bengaluru-peenya',
    locationName: 'Peenya 4th Phase Machinery Hub',
    city: 'Bengaluru',
    coordinates: { lat: 13.0285, lng: 77.5195 },
    currentAqi: 168,
    predictedAqi: 195,
    expectedDurationHours: '2–4 hours',
    risk: 'MODERATE',
    suggestedResponse: 'Direct road dampening along unpaved factory perimeter',
    status: 'ACKNOWLEDGED',
    createdAt: new Date(Date.now() - 110 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 40 * 60000).toISOString(),
    assignedAuthority: 'KSPCB Bengaluru West',
    actionLog: [
      { status: 'DETECTED', updatedAt: new Date(Date.now() - 110 * 60000).toISOString(), actor: 'AEROVEDA Engine', note: 'Dust suspension threshold reached' },
      { status: 'ALERT_SENT', updatedAt: new Date(Date.now() - 80 * 60000).toISOString(), actor: 'Dispatch System', note: 'Municipal dampening request dispatched' },
      { status: 'ACKNOWLEDGED', updatedAt: new Date(Date.now() - 40 * 60000).toISOString(), actor: 'BBMP Dust Wing', note: 'Water sprinkler truck en route' },
    ],
  },
  {
    id: 'alert-haldia-08',
    title: 'Haldia Dock Complex Bulk Berth',
    hotspotId: 'hotspot-kolkata-haldia',
    locationName: 'Haldia Dock Complex Bulk Berth',
    city: 'Kolkata',
    coordinates: { lat: 22.0624, lng: 88.0645 },
    currentAqi: 260,
    predictedAqi: 290,
    expectedDurationHours: '4–7 hours',
    risk: 'HIGH',
    suggestedResponse: 'Dry coal handling dust screen check',
    status: 'ALERT_SENT',
    createdAt: new Date(Date.now() - 55 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 25 * 60000).toISOString(),
    assignedAuthority: 'West Bengal Pollution Control Board & Port Trust',
    actionLog: [
      { status: 'DETECTED', updatedAt: new Date(Date.now() - 55 * 60000).toISOString(), actor: 'AEROVEDA Detection Engine', note: 'Aerosol surge' },
      { status: 'ALERT_SENT', updatedAt: new Date(Date.now() - 25 * 60000).toISOString(), actor: 'Dispatch Gateway', note: 'Port environmental desk notified' },
    ],
  },
];

export const initialCityForecasts: Record<string, CityForecast> = {
  pune: {
    cityId: 'pune',
    cityName: 'Pune',
    currentAqi: 172,
    spikeForecastPercentage: 38,
    forecastPeriod: 'next 6 hours',
    dominantFactor: 'Industrial activity + nocturnal calm wind',
    predictionDrivers: [
      {
        name: 'Industrial activity',
        impact: 'HIGH',
        trend: 'increasing',
        detail: 'Bhosari & Chakan night shifts starting boiler combustion cycles.',
      },
      {
        name: 'Wind conditions',
        impact: 'HIGH',
        trend: 'stagnant',
        detail: 'Ground surface wind decaying to < 1.5 km/h, preventing horizontal ventilation.',
      },
      {
        name: 'Temperature inversion',
        impact: 'MEDIUM',
        trend: 'increasing',
        detail: 'Post-sunset cooling cap trapping ground emissions below 120m.',
      },
      {
        name: 'Satellite anomaly',
        impact: 'MEDIUM',
        trend: 'stagnant',
        detail: 'Elevated aerosol optical depth plume drifting southeast.',
      },
      {
        name: 'Historical patterns',
        impact: 'LOW',
        trend: 'stagnant',
        detail: 'Seasonal Tuesday-to-Thursday industrial throughput crest.',
      },
    ],
    hourlyProjections: [
      { timeLabel: 'Now', hoursAhead: 0, aqi: 172, confidenceInterval: [168, 176] },
      { timeLabel: '2h', hoursAhead: 2, aqi: 188, confidenceInterval: [180, 196] },
      { timeLabel: '4h', hoursAhead: 4, aqi: 221, confidenceInterval: [210, 232] },
      { timeLabel: '6h', hoursAhead: 6, aqi: 258, confidenceInterval: [242, 274] },
      { timeLabel: '12h', hoursAhead: 12, aqi: 235, confidenceInterval: [215, 255] },
      { timeLabel: '24h', hoursAhead: 24, aqi: 180, confidenceInterval: [160, 200] },
      { timeLabel: '48h', hoursAhead: 48, aqi: 155, confidenceInterval: [135, 175] },
    ],
    advisoryNote: 'Simulated multi-variate LSTM forecast indicating a +38% surge within 6 hours. High risk of sensitive population discomfort in Pimpri-Chinchwad.',
    lastCalculated: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  delhi: {
    cityId: 'delhi',
    cityName: 'Delhi (NCR)',
    currentAqi: 342,
    spikeForecastPercentage: 24,
    forecastPeriod: 'next 6 hours',
    dominantFactor: 'Regional agricultural burning drift + severe inversion',
    predictionDrivers: [
      { name: 'Upwind biomass burning', impact: 'HIGH', trend: 'increasing', detail: 'North-western stubble smoke transport vector active.' },
      { name: 'Boundary layer inversion', impact: 'HIGH', trend: 'stagnant', detail: 'Inversion lid height compressed to 70m.' },
      { name: 'Heavy vehicular transit', impact: 'HIGH', trend: 'increasing', detail: 'Night freight border entry rush.' },
      { name: 'Calm surface winds', impact: 'MEDIUM', trend: 'stagnant', detail: 'Wind speed 0.8 km/h, zero lateral clearance.' },
    ],
    hourlyProjections: [
      { timeLabel: 'Now', hoursAhead: 0, aqi: 342, confidenceInterval: [335, 350] },
      { timeLabel: '2h', hoursAhead: 2, aqi: 368, confidenceInterval: [355, 380] },
      { timeLabel: '4h', hoursAhead: 4, aqi: 398, confidenceInterval: [382, 414] },
      { timeLabel: '6h', hoursAhead: 6, aqi: 424, confidenceInterval: [405, 442] },
      { timeLabel: '12h', hoursAhead: 12, aqi: 375, confidenceInterval: [350, 400] },
      { timeLabel: '24h', hoursAhead: 24, aqi: 310, confidenceInterval: [285, 335] },
      { timeLabel: '48h', hoursAhead: 48, aqi: 260, confidenceInterval: [230, 290] },
    ],
    advisoryNote: 'Severe category advisory. GRAP Phase-IV emergency protocols active in simulation.',
    lastCalculated: new Date(Date.now() - 8 * 60000).toISOString(),
  },
  mumbai: {
    cityId: 'mumbai',
    cityName: 'Mumbai',
    currentAqi: 185,
    spikeForecastPercentage: 18,
    forecastPeriod: 'next 6 hours',
    dominantFactor: 'Sea breeze withdrawal + coastal refinery flaring',
    predictionDrivers: [
      { name: 'Sea breeze transition', impact: 'HIGH', trend: 'decreasing', detail: 'Land-sea breeze reversal setting in at dusk.' },
      { name: 'Refinery flaring', impact: 'MEDIUM', trend: 'stagnant', detail: 'Continuous SO2 venting in Chembur-Trombay sector.' },
      { name: 'Metro construction dust', impact: 'MEDIUM', trend: 'increasing', detail: 'Dry mechanical drilling across central corridor.' },
    ],
    hourlyProjections: [
      { timeLabel: 'Now', hoursAhead: 0, aqi: 185, confidenceInterval: [180, 190] },
      { timeLabel: '2h', hoursAhead: 2, aqi: 196, confidenceInterval: [188, 204] },
      { timeLabel: '4h', hoursAhead: 4, aqi: 212, confidenceInterval: [200, 224] },
      { timeLabel: '6h', hoursAhead: 6, aqi: 218, confidenceInterval: [205, 230] },
      { timeLabel: '12h', hoursAhead: 12, aqi: 175, confidenceInterval: [160, 190] },
      { timeLabel: '24h', hoursAhead: 24, aqi: 150, confidenceInterval: [135, 165] },
      { timeLabel: '48h', hoursAhead: 48, aqi: 130, confidenceInterval: [115, 145] },
    ],
    advisoryNote: 'Moderate to Poor transition expected in coastal harbor wards during overnight hours.',
    lastCalculated: new Date(Date.now() - 12 * 60000).toISOString(),
  },
  ahmedabad: {
    cityId: 'ahmedabad',
    cityName: 'Ahmedabad',
    currentAqi: 215,
    spikeForecastPercentage: 26,
    forecastPeriod: 'next 6 hours',
    dominantFactor: 'Chemical boilers + dry soil particulate suspension',
    predictionDrivers: [
      { name: 'Industrial activity', impact: 'HIGH', trend: 'increasing', detail: 'Vatva and Narol textile dye manufacturing.' },
      { name: 'Arid wind suspension', impact: 'MEDIUM', trend: 'stagnant', detail: 'Fine dust carried from peripheral bypass routes.' },
    ],
    hourlyProjections: [
      { timeLabel: 'Now', hoursAhead: 0, aqi: 215, confidenceInterval: [208, 222] },
      { timeLabel: '2h', hoursAhead: 2, aqi: 235, confidenceInterval: [225, 245] },
      { timeLabel: '4h', hoursAhead: 4, aqi: 258, confidenceInterval: [246, 270] },
      { timeLabel: '6h', hoursAhead: 6, aqi: 271, confidenceInterval: [256, 286] },
      { timeLabel: '12h', hoursAhead: 12, aqi: 220, confidenceInterval: [202, 238] },
      { timeLabel: '24h', hoursAhead: 24, aqi: 175, confidenceInterval: [160, 190] },
      { timeLabel: '48h', hoursAhead: 48, aqi: 150, confidenceInterval: [135, 165] },
    ],
    advisoryNote: 'Predicted spike into High Risk bracket (+26%) due to boiler shift changes and low nighttime dispersion.',
    lastCalculated: new Date(Date.now() - 15 * 60000).toISOString(),
  },
};

export const initialCitizenReports: CitizenReport[] = [
  {
    id: 'report-01',
    imageUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="100%" height="100%" fill="%23e2e8f0"/><circle cx="200" cy="180" r="90" fill="%2364748b" opacity="0.6"/><path d="M120 220 C 160 140, 240 140, 280 220 Z" fill="%23475569"/><text x="50%" y="40" font-family="sans-serif" font-size="14" fill="%23334155" text-anchor="middle">Photographic Observation: Heavy Dark Smoke</text><text x="50%" y="280" font-family="sans-serif" font-size="12" fill="%2364748b" text-anchor="middle">Location: Bhosari MIDC, Pune</text></svg>',
    locationName: 'Bhosari MIDC Sector 7',
    city: 'Pune',
    coordinates: { lat: 18.6322, lng: 73.8415 },
    observationType: 'Industrial emission',
    reportedBy: 'Kunal Deshmukh (Resident Officer)',
    timestamp: new Date(Date.now() - 35 * 60000).toISOString(),
    status: 'VERIFIED',
    aiAnalysis: {
      identifiedType: 'High-density industrial emission plume',
      confidence: 93,
      risk: 'HIGH',
      affectedAreaKm: 14.2,
      extractedKeyFeatures: [
        'Dark opaque particulate discharge from unscrubbed stack',
        'Estimated thermal plume height: 42 meters',
        'Downwind drift vector towards residential cluster Sector 4',
      ],
      summary: 'Computer vision analysis identified heavy particulate exhaust with thermal soot characteristics.',
    },
  },
  {
    id: 'report-02',
    imageUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="100%" height="100%" fill="%23fef3c7"/><circle cx="180" cy="190" r="70" fill="%23d97706" opacity="0.5"/><path d="M100 240 Q 200 120 300 240 Z" fill="%23b45309" opacity="0.7"/><text x="50%" y="40" font-family="sans-serif" font-size="14" fill="%2378350f" text-anchor="middle">Agricultural Residue Stubble Smoke</text><text x="50%" y="280" font-family="sans-serif" font-size="12" fill="%2392400e" text-anchor="middle">Location: Chakan Rural Periphery, Pune</text></svg>',
    locationName: 'Chakan Peripheral Farmlands',
    city: 'Pune',
    coordinates: { lat: 18.7594, lng: 73.8612 },
    observationType: 'Agricultural burning',
    reportedBy: 'Amrita Patil (Ward Volunteer)',
    timestamp: new Date(Date.now() - 85 * 60000).toISOString(),
    status: 'VERIFIED',
    aiAnalysis: {
      identifiedType: 'Potential agricultural burning',
      confidence: 87,
      risk: 'HIGH',
      affectedAreaKm: 12.0,
      extractedKeyFeatures: [
        'Broad open-field biomass combustion',
        'Visible white-gray smoke column characteristic of crop stubble',
        'Ground thermal anomaly correlated with satellite hotspot grid',
      ],
      summary: 'Confirmed open-field biomass combustion spreading over 12 km dispersion footprint under low wind speeds.',
    },
  },
  {
    id: 'report-03',
    imageUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="100%" height="100%" fill="%23f1f5f9"/><rect x="50" y="180" width="300" height="80" fill="%2394a3b8" opacity="0.8"/><text x="50%" y="40" font-family="sans-serif" font-size="14" fill="%23334155" text-anchor="middle">Uncovered Municipal Waste Combustion</text><text x="50%" y="280" font-family="sans-serif" font-size="12" fill="%2364748b" text-anchor="middle">Location: Pimpri Railway Crossing</text></svg>',
    locationName: 'Pimpri Railway Crossing',
    city: 'Pune',
    coordinates: { lat: 18.6275, lng: 73.8012 },
    observationType: 'Waste burning',
    reportedBy: 'Sanjay Shinde (Citizen)',
    timestamp: new Date(Date.now() - 140 * 60000).toISOString(),
    status: 'VERIFIED',
    aiAnalysis: {
      identifiedType: 'Municipal solid waste combustion',
      confidence: 89,
      risk: 'HIGH',
      affectedAreaKm: 5.5,
      extractedKeyFeatures: [
        'Toxic dioxin/furan risk signature',
        'Open low-temperature plastic pyrolysis detected in spectrum',
      ],
      summary: 'Direct community hazard. High priority municipal fire dispatch triggered.',
    },
  },
];

export const initialSensors: SensorObservation[] = [
  {
    id: 'sensor-pune-bhosari',
    stationName: 'Bhosari MIDC IoT Node #04',
    city: 'Pune',
    coordinates: { lat: 18.634, lng: 73.839 },
    pm25: 148,
    pm10: 210,
    no2: 84,
    so2: 42,
    co: 2.4,
    aqi: 287,
    temperatureC: 24.2,
    humidityPct: 62,
    windSpeedKmh: 1.8,
    windDirectionDeg: 65,
    status: 'anomaly',
    lastUpdated: '2 min ago',
  },
  {
    id: 'sensor-pune-chakan',
    stationName: 'Chakan Auto Hub Node #09',
    city: 'Pune',
    coordinates: { lat: 18.756, lng: 73.855 },
    pm25: 132,
    pm10: 195,
    no2: 76,
    so2: 38,
    co: 1.9,
    aqi: 242,
    temperatureC: 23.8,
    humidityPct: 65,
    windSpeedKmh: 2.1,
    windDirectionDeg: 80,
    status: 'active',
    lastUpdated: '1 min ago',
  },
  {
    id: 'sensor-pune-shivajinagar',
    stationName: 'Shivajinagar Urban Observatory',
    city: 'Pune',
    coordinates: { lat: 18.531, lng: 73.844 },
    pm25: 64,
    pm10: 110,
    no2: 42,
    so2: 18,
    co: 1.1,
    aqi: 142,
    temperatureC: 25.5,
    humidityPct: 58,
    windSpeedKmh: 3.4,
    windDirectionDeg: 90,
    status: 'active',
    lastUpdated: '4 min ago',
  },
  {
    id: 'sensor-delhi-anand-vihar',
    stationName: 'CPCB Anand Vihar Continuous Station',
    city: 'Delhi',
    coordinates: { lat: 28.647, lng: 77.315 },
    pm25: 234,
    pm10: 380,
    no2: 118,
    so2: 56,
    co: 4.8,
    aqi: 384,
    temperatureC: 22.0,
    humidityPct: 74,
    windSpeedKmh: 0.9,
    windDirectionDeg: 310,
    status: 'anomaly',
    lastUpdated: '3 min ago',
  },
  {
    id: 'sensor-mumbai-chembur',
    stationName: 'Chembur Refining Periphery Monitor',
    city: 'Mumbai',
    coordinates: { lat: 19.019, lng: 72.906 },
    pm25: 115,
    pm10: 165,
    no2: 78,
    so2: 89,
    co: 2.1,
    aqi: 245,
    temperatureC: 27.8,
    humidityPct: 82,
    windSpeedKmh: 4.2,
    windDirectionDeg: 240,
    status: 'anomaly',
    lastUpdated: '2 min ago',
  },
  {
    id: 'sensor-ahmedabad-vatva',
    stationName: 'Vatva GIDC Continuous Monitoring Node',
    city: 'Ahmedabad',
    coordinates: { lat: 22.955, lng: 72.631 },
    pm25: 138,
    pm10: 225,
    no2: 95,
    so2: 48,
    co: 2.6,
    aqi: 272,
    temperatureC: 26.4,
    humidityPct: 52,
    windSpeedKmh: 2.5,
    windDirectionDeg: 120,
    status: 'anomaly',
    lastUpdated: '5 min ago',
  },
  {
    id: 'sensor-bengaluru-peenya',
    stationName: 'Peenya Microclimate Station B4',
    city: 'Bengaluru',
    coordinates: { lat: 13.029, lng: 77.518 },
    pm25: 78,
    pm10: 142,
    no2: 48,
    so2: 22,
    co: 1.4,
    aqi: 168,
    temperatureC: 23.2,
    humidityPct: 68,
    windSpeedKmh: 5.1,
    windDirectionDeg: 140,
    status: 'active',
    lastUpdated: '1 min ago',
  },
  {
    id: 'sensor-hyderabad-patancheru',
    stationName: 'Patancheru Pharma Hub Node',
    city: 'Hyderabad',
    coordinates: { lat: 17.527, lng: 78.266 },
    pm25: 110,
    pm10: 172,
    no2: 72,
    so2: 36,
    co: 1.8,
    aqi: 238,
    temperatureC: 25.8,
    humidityPct: 60,
    windSpeedKmh: 2.8,
    windDirectionDeg: 180,
    status: 'anomaly',
    lastUpdated: '3 min ago',
  },
];

export const initialFederatedCities: FederatedCityNode[] = [
  {
    id: 'fed-mumbai',
    name: 'Mumbai',
    state: 'Maharashtra',
    coordinates: { lat: 19.076, lng: 72.8777 },
    status: 'ACTIVE',
    localSamplesCount: 142800,
    lastModelUpdate: '18 min ago',
    localAqiMean: 185,
    privacyEpsilon: 0.42,
    modelVersion: 'v2.8.4',
    accuracy: 94.2,
  },
  {
    id: 'fed-pune',
    name: 'Pune',
    state: 'Maharashtra',
    coordinates: { lat: 18.5204, lng: 73.8567 },
    status: 'SYNCED',
    localSamplesCount: 98600,
    lastModelUpdate: '6 min ago',
    localAqiMean: 212,
    privacyEpsilon: 0.38,
    modelVersion: 'v2.8.4',
    accuracy: 93.8,
  },
  {
    id: 'fed-ahmedabad',
    name: 'Ahmedabad',
    state: 'Gujarat',
    coordinates: { lat: 23.0225, lng: 72.5714 },
    status: 'ACTIVE',
    localSamplesCount: 89400,
    lastModelUpdate: '24 min ago',
    localAqiMean: 228,
    privacyEpsilon: 0.45,
    modelVersion: 'v2.8.3',
    accuracy: 92.5,
  },
  {
    id: 'fed-delhi',
    name: 'Delhi',
    state: 'National Capital Region',
    coordinates: { lat: 28.6139, lng: 77.209 },
    status: 'TRAINING',
    localSamplesCount: 284500,
    lastModelUpdate: '3 min ago',
    localAqiMean: 324,
    privacyEpsilon: 0.52,
    modelVersion: 'v2.8.4-rc2',
    accuracy: 95.1,
  },
  {
    id: 'fed-bengaluru',
    name: 'Bengaluru',
    state: 'Karnataka',
    coordinates: { lat: 12.9716, lng: 77.5946 },
    status: 'SYNCED',
    localSamplesCount: 112000,
    lastModelUpdate: '42 min ago',
    localAqiMean: 138,
    privacyEpsilon: 0.35,
    modelVersion: 'v2.8.4',
    accuracy: 93.1,
  },
  {
    id: 'fed-hyderabad',
    name: 'Hyderabad',
    state: 'Telangana',
    coordinates: { lat: 17.385, lng: 78.4867 },
    status: 'ACTIVE',
    localSamplesCount: 104500,
    lastModelUpdate: '15 min ago',
    localAqiMean: 176,
    privacyEpsilon: 0.41,
    modelVersion: 'v2.8.4',
    accuracy: 92.9,
  },
  {
    id: 'fed-chennai',
    name: 'Chennai',
    state: 'Tamil Nadu',
    coordinates: { lat: 13.0827, lng: 80.2707 },
    status: 'SYNCED',
    localSamplesCount: 96300,
    lastModelUpdate: '55 min ago',
    localAqiMean: 142,
    privacyEpsilon: 0.36,
    modelVersion: 'v2.8.3',
    accuracy: 91.8,
  },
  {
    id: 'fed-kolkata',
    name: 'Kolkata',
    state: 'West Bengal',
    coordinates: { lat: 22.5726, lng: 88.3639 },
    status: 'ACTIVE',
    localSamplesCount: 128900,
    lastModelUpdate: '29 min ago',
    localAqiMean: 232,
    privacyEpsilon: 0.44,
    modelVersion: 'v2.8.4',
    accuracy: 93.4,
  },
  {
    id: 'fed-nagpur',
    name: 'Nagpur',
    state: 'Maharashtra',
    coordinates: { lat: 21.1458, lng: 79.0882 },
    status: 'STANDBY',
    localSamplesCount: 64200,
    lastModelUpdate: '2 hours ago',
    localAqiMean: 154,
    privacyEpsilon: 0.32,
    modelVersion: 'v2.8.2',
    accuracy: 90.7,
  },
  {
    id: 'fed-lucknow',
    name: 'Lucknow',
    state: 'Uttar Pradesh',
    coordinates: { lat: 26.8467, lng: 80.9462 },
    status: 'TRAINING',
    localSamplesCount: 152000,
    lastModelUpdate: '11 min ago',
    localAqiMean: 268,
    privacyEpsilon: 0.48,
    modelVersion: 'v2.8.4-rc1',
    accuracy: 93.6,
  },
  {
    id: 'fed-jaipur',
    name: 'Jaipur',
    state: 'Rajasthan',
    coordinates: { lat: 26.9124, lng: 75.7873 },
    status: 'ACTIVE',
    localSamplesCount: 78500,
    lastModelUpdate: '38 min ago',
    localAqiMean: 194,
    privacyEpsilon: 0.39,
    modelVersion: 'v2.8.3',
    accuracy: 91.4,
  },
  {
    id: 'fed-patna',
    name: 'Patna',
    state: 'Bihar',
    coordinates: { lat: 25.5941, lng: 85.1376 },
    status: 'ACTIVE',
    localSamplesCount: 134000,
    lastModelUpdate: '20 min ago',
    localAqiMean: 285,
    privacyEpsilon: 0.47,
    modelVersion: 'v2.8.4',
    accuracy: 92.8,
  },
];

export const initialModelUpdates: FederatedModelUpdate[] = [
  {
    id: 'upd-1284',
    roundNumber: 428,
    participatingCity: 'Pune (Bhosari Node)',
    gradientNorm: 0.0482,
    lossReduction: 0.0142,
    weightsDelta: 'ΔW[GNN_Layer3]: -0.0124, ΔW[LSTM_Hidden]: +0.0089',
    timestamp: '6 min ago',
    status: 'AGGREGATED',
  },
  {
    id: 'upd-1283',
    roundNumber: 428,
    participatingCity: 'Delhi (NCR Central)',
    gradientNorm: 0.0914,
    lossReduction: 0.0285,
    weightsDelta: 'ΔW[GNN_Layer3]: -0.0241, ΔW[LSTM_Hidden]: +0.0175',
    timestamp: '9 min ago',
    status: 'AGGREGATED',
  },
  {
    id: 'upd-1282',
    roundNumber: 427,
    participatingCity: 'Hyderabad (Patancheru)',
    gradientNorm: 0.0521,
    lossReduction: 0.0118,
    weightsDelta: 'ΔW[SpatialKernel]: +0.0064, ΔW[TemporalCell]: -0.0091',
    timestamp: '22 min ago',
    status: 'VERIFIED',
  },
  {
    id: 'upd-1281',
    roundNumber: 427,
    participatingCity: 'Mumbai (Chembur Gateway)',
    gradientNorm: 0.0618,
    lossReduction: 0.0162,
    weightsDelta: 'ΔW[CoastalBias]: -0.0140, ΔW[InversionCell]: +0.0112',
    timestamp: '35 min ago',
    status: 'VERIFIED',
  },
];

export const initialEvents: EnvironmentalEvent[] = [
  {
    id: 'ev-01',
    type: 'SPIKE',
    title: 'Pune Industrial Corridor PM2.5 Spike',
    location: 'Bhosari-Chakan Logistics Belt, Pune',
    city: 'Pune',
    severity: 'HIGH',
    timestamp: '14 min ago',
    description: 'Rapid particulate escalation reaching 287 AQI under calm 1.8 km/h wind stagnation.',
  },
  {
    id: 'ev-02',
    type: 'ANOMALY',
    title: 'Anand Vihar Inversion Trap',
    location: 'Delhi-Ghaziabad Transit Frontier, Delhi',
    city: 'Delhi',
    severity: 'CRITICAL',
    timestamp: '28 min ago',
    description: 'Nocturnal boundary layer dropped to 80m trapping regional diesel and biomass emissions.',
  },
  {
    id: 'ev-03',
    type: 'REPORT',
    title: 'Citizen Observation Verified',
    location: 'Bhosari Sector 7, Pune',
    city: 'Pune',
    severity: 'HIGH',
    timestamp: '35 min ago',
    description: 'Photographic evidence of unscrubbed stack discharge verified with 93% AI confidence.',
  },
  {
    id: 'ev-04',
    type: 'STAGNATION',
    title: 'Micro-Valley Thermal Stagnation',
    location: 'Pimpri-Chinchwad Basin',
    city: 'Pune',
    severity: 'HIGH',
    timestamp: '52 min ago',
    description: 'Atmospheric ventilation index decreased to 410 m²/s triggering elevated dispersion risk.',
  },
];
